name: Automatically Deployment

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Environment Variables File for Production
        env:
          NEXT_PUBLIC_WEB_VERSION: ${{  github.ref_name }}

      # Install project dependencies, test and build
      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
