name: Automatically Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install project dependencies, test and build
      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build
